#!/usr/bin/env bash

staged=$(git diff --cached --name-only --diff-filter=ACM)
if [ -n "$staged" ]; then
  echo "[pre-commit] Running oxfmt on staged files..."
  echo "$staged" | xargs bunx oxfmt
  echo "$staged" | xargs git add
fi

# NOTE: these checks are commented out because they take too long to run on
# every commit. maybe we will return to them later.

# echo "[pre-commit] Running quality checks..."
# for some reason, unable to run the entire check:* suite with `bun run
# --sequential check:*`. unfortunate. must now keep in sync with all check
# scripts in package.json.
# bun run --sequential check:fmt
# bun run --sequential check:lint
# bun run --sequential check:types
# bun run --sequential check:test
